std = "lua51"
max_line_length = false
exclude_files = { ".release" }

globals = {
    "DynamicDisplayNameplateDB",
    "SLASH_DDNDEFICIT1",
    "SLASH_DDNENEMIES1",
    "SLASH_DDNENGAGED1",
    "SLASH_DDNFADEFULL1",
    "SLASH_DDNFRIENDS1",
    "SLASH_DDNGROUP1",
    "SLASH_DDNHELP1",
    "SLASH_DDNOPTIONS1",
    "SLASH_DDNSHOWHURT1",
    "SLASH_DDNSIDES1",
    "SLASH_DDNSTATUS1",
    "SLASH_DDNWATCH1",
    "SlashCmdList",
}

read_globals = {
    "AbbreviateNumbers",
    "C_AddOns",
    "C_Console",
    "C_CurveUtil",
    "C_CVar",
    "C_NamePlate",
    "CreateFrame",
    "GetCVar",
    "GetNumGroupMembers",
    "GetNumSubgroupMembers",
    "InCombatLockdown",
    "IsAddOnLoaded",
    "InterfaceOptions_AddCategory",
    "InterfaceOptionsFrame_OpenToCategory",
    "IsInRaid",
    "issecretvalue",
    "SetCVar",
    "Settings",
    "STANDARD_TEXT_FONT",
    "UnitHealthMissing",
    "UnitHealthPercent",
    "UnitInParty",
    "UnitInRaid",
    "UnitIsFriend",
    "UnitIsPlayer",
    "UnitIsUnit",
    "UnitPlayerOrPetInParty",
    "UnitPlayerOrPetInRaid",
    "UnitThreatSituation",
}
